-- total revenue generated by each staff member
SELECT
    o.staff_id,
    SUM(oi.quantity * oi.list_price * (1 - oi.discount)) AS total_revenue
FROM orders o
JOIN order_item oi ON o.order_id = oi.order_id
GROUP BY o.staff_id;